# Generated by Django 4.0.5 on 2022-07-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IS.objectives'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IS.perspective'),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='perspective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IS.perspective'),
        ),
    ]
