# Generated by Django 4.0.5 on 2022-07-04 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.objectives'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
