# Generated by Django 4.0.5 on 2022-06-10 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perspective',
            fields=[
                ('perspective_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perspective_name', models.CharField(max_length=120)),
                ('perspective_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('objective_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective_name', models.CharField(max_length=120)),
                ('objective_weight', models.FloatField()),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=50, verbose_name='Type')),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.perspective')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('kpi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_name', models.CharField(max_length=120)),
                ('kpi_weight', models.FloatField()),
                ('kpi_unit_measurement', models.CharField(choices=[('Percentage', 'Percentage'), ('ETB', 'ETB'), ('USD', 'USD'), ('Numbers', 'Numbers'), ('Levels', 'Levels')], default='Percentage', max_length=50, verbose_name='kpi_unit_measurement')),
                ('kpi_target', models.FloatField(blank=True)),
                ('kpi_actual', models.FloatField(blank=True, null=True)),
                ('January', models.FloatField(blank=True, null=True)),
                ('February', models.FloatField(blank=True, null=True)),
                ('March', models.FloatField(blank=True, null=True)),
                ('April', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('June', models.FloatField(blank=True, null=True)),
                ('July', models.FloatField(blank=True, null=True)),
                ('August', models.FloatField(blank=True, null=True)),
                ('September', models.FloatField(blank=True, null=True)),
                ('October', models.FloatField(blank=True, null=True)),
                ('November', models.FloatField(blank=True, null=True)),
                ('December', models.FloatField(blank=True, null=True)),
                ('Score_January', models.FloatField(blank=True, default=0)),
                ('Score_February', models.FloatField(blank=True, default=0)),
                ('Score_March', models.FloatField(blank=True, default=0)),
                ('Score_April', models.FloatField(blank=True, default=0)),
                ('Score_May', models.FloatField(blank=True, default=0)),
                ('Score_June', models.FloatField(blank=True, default=0)),
                ('Score_July', models.FloatField(blank=True, default=0)),
                ('Score_August', models.FloatField(blank=True, default=0)),
                ('Score_September', models.FloatField(blank=True, default=0)),
                ('Score_October', models.FloatField(blank=True, default=0)),
                ('Score_November', models.FloatField(blank=True, default=0)),
                ('Score_December', models.FloatField(blank=True, default=0)),
                ('aggregate', models.FloatField(blank=True, default=0)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.objectives')),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.perspective')),
            ],
        ),
    ]
