# Generated by Django 4.0.5 on 2022-06-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectives',
            name='month',
        ),
    ]
