# Generated by Django 4.0.5 on 2022-06-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0004_remove_kpi_kpi_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='April',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='August',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='December',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='February',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='January',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='July',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='June',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='March',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='May',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='November',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='October',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='September',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
