# Generated by Django 4.0.5 on 2022-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0006_kpi_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='vp_bod_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_cooperative_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_corporate_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_credit_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_finance_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_hc_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_ifb_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_internal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_is_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_legal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_risk_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_strategy_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perspective',
            name='vp_tech_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perspective',
            name='perspective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
