# Generated by Django 4.0.5 on 2022-07-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0007_perspective_vp_bod_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_bod_weight',
            new_name='vp_bod_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_cooperative_weight',
            new_name='vp_cooperative_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_corporate_weight',
            new_name='vp_corporate_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_credit_weight',
            new_name='vp_credit_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_finance_weight',
            new_name='vp_finance_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_hc_weight',
            new_name='vp_hc_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_ifb_weight',
            new_name='vp_ifb_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_internal_weight',
            new_name='vp_internal_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_is_weight',
            new_name='vp_is_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_legal_weight',
            new_name='vp_legal_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_risk_weight',
            new_name='vp_risk_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_strategy_weight',
            new_name='vp_strategy_perspective_weight',
        ),
        migrations.RenameField(
            model_name='perspective',
            old_name='vp_tech_weight',
            new_name='vp_tech_perspective_weight',
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_bodobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_cooperativeobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_corporateobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_creditobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_financeobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_hcobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_ifbobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_internalobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_isobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_legalobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_riskobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_strategyobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectives',
            name='vp_techobjective_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
