# Generated by Django 4.0.5 on 2022-07-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0008_rename_vp_bod_weight_perspective_vp_bod_perspective_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectives',
            name='vp_bodobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_cooperativeobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_corporateobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_creditobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_financeobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_hcobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_ifbobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_internalobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_isobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_legalobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_riskobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_strategyobjective_weight',
        ),
        migrations.RemoveField(
            model_name='objectives',
            name='vp_techobjective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_bod_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_cooperative_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_corporate_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_credit_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_finance_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_hc_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_ifb_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_internal_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_is_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_legal_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_risk_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_strategy_perspective_weight',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='vp_tech_perspective_weight',
        ),
    ]
