# Generated by Django 4.0.5 on 2022-07-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0009_alter_kpi_user'),
        ('bsc', '0012_alter_kpi_kpi_target_alter_kpi_kpi_weight'),
    ]

    operations = [
    ]
