# Generated by Django 4.0.5 on 2022-07-25 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsc', '0013_merge_20220711_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
